import type { SiteContent } from "./types";

const unsplash = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const defaultContent: SiteContent = {
  site: {
    name: "Elara Voss",
    email: "hello@elaravoss.com",
    location: "Berlin, Germany",
    instagram: "@elaravoss.photo",
    twitter: "@elaravoss",
    behance: "Elara Voss",
    bookingNote:
      "Currently accepting commissions for Q1 2027. Inquiries welcome for Q4 2026 on a case-by-case basis.",
  },
  hero: {
    eyebrow: "Fine Art Photography",
    headline: "Light finds its",
    headlineItalic: "own geometry.",
  },
  about: {
    heading: "Elara Voss",
    teaser:
      "Berlin-based photographer working in portraiture and landscape. Fifteen years of looking for the minute before and the minute after, when a subject reveals something unguarded. Published in Foam Magazine, The British Journal of Photography and Le Monde.",
    paragraphs: [
      "Born in Hamburg, currently based in Berlin. Elara began making photographs at seventeen with a borrowed Rolleiflex, drawn to the way medium format film compressed time into a single held breath.",
      "Over fifteen years she has developed a body of work that refuses the decisive moment in favor of something quieter — the minute before and the minute after, when a subject is most themselves.",
      "Her work has appeared in Foam Magazine, The British Journal of Photography, Aperture Online, and Le Monde M. She has exhibited at Foam Amsterdam, C/O Berlin, and Rencontres d'Arles.",
    ],
    portrait: unsplash("photo-1494790108377-be9c29b29330", 1400),
  },
  photos: [
    {
      id: "quiet-study",
      src: unsplash("photo-1544005313-94ddf0286df2"),
      title: "Quiet Study",
      category: "Portraits",
      width: 4,
      height: 5,
      featured: false,
      hero: true,
    },
    {
      id: "into-the-fog",
      src: unsplash("photo-1448375240586-882707db888b"),
      title: "Into the Fog",
      category: "Landscapes",
      width: 16,
      height: 9,
      featured: true,
      hero: true,
    },
    {
      id: "crimson",
      src: unsplash("photo-1438761681033-6461ffad8d80"),
      title: "Crimson",
      category: "Portraits",
      width: 4,
      height: 5,
      featured: true,
      hero: false,
    },
    {
      id: "after-hours",
      src: unsplash("photo-1509631179647-0177331693ae"),
      title: "After Hours",
      category: "Editorial",
      width: 3,
      height: 4,
      featured: true,
      hero: false,
    },
    {
      id: "green-hills",
      src: unsplash("photo-1500382017468-9049fed747ef"),
      title: "Green Hills",
      category: "Landscapes",
      width: 4,
      height: 3,
      featured: true,
      hero: false,
    },
    {
      id: "night-shift",
      src: unsplash("photo-1529139574466-a303027c1d8b"),
      title: "Night Shift",
      category: "Editorial",
      width: 3,
      height: 4,
      featured: false,
      hero: true,
    },
    {
      id: "last-light",
      src: unsplash("photo-1506905925346-21bda4d32df4"),
      title: "Last Light",
      category: "Landscapes",
      width: 4,
      height: 3,
      featured: false,
      hero: false,
    },
    {
      id: "silver",
      src: unsplash("photo-1517841905240-472988babdf9"),
      title: "Silver",
      category: "Portraits",
      width: 4,
      height: 3,
      featured: false,
      hero: false,
    },
    {
      id: "black-study",
      src: unsplash("photo-1488426862026-3ee34a7d66df"),
      title: "Black Study",
      category: "Portraits",
      width: 4,
      height: 5,
      featured: false,
      hero: false,
    },
    {
      id: "velvet",
      src: unsplash("photo-1515886657613-9f3515b0c78f"),
      title: "Velvet",
      category: "Editorial",
      width: 3,
      height: 4,
      featured: false,
      hero: false,
    },
  ],
};
